### ISSUE TITLE
Question screen template

### ISSUE THREAD

**Issue by martsimon** [FRCC-CSC234/MCIGame#6]
Code up a template for what the question screen will look like- doesn't need real MCI questions, can just be like 2+2 or whatever

**Comment by b-ju** [comment]
If it's ok with everyone I will work on this template. 

Some ideas:
I am thinking it will have 4 buttons, 1 for each answer choice and the user will press arrow keys (up/down) to highlight/select an answer then press enter on the answer they want to choose. 
It will then flash red or green background if they choose correct answer or not.
               -background could be something funny like a crying baby for wrong answer 
               - any ideas for if they get correct answer?
If they choose wrong answer just make them choose again ?
If they choose right answer proceed to next level.
